const books = [
    {
      book_id: book[0].id,
      name: 'Book0_Name',
      author_id: 'A647453',
      author_name: 'Author0Name',
      published_year: 2013,
      book_code: '0006486142',
      country_origin: 'India',
      desc: 'The Mad Ship',
      genre: 'fiction',
      type: 'Journal',
      digital_link: 'https://test.com/Book0_Name.pdf',
      amount: 15795,
      status: 'pending',
      tags: ['fiction', 'India', 'Journal'],
      date_added: '2022-12-06',
      date_published: '2023-07-02',
    },
    {
      book_id: book[1].id,
      name: 'Book1_Name',
      author_id: 'A872983',
      author_name: 'Author1Name',
      published_year: 2021,
      book_code: '0006754899',
      country_origin: 'Germany',
      desc: 'The Lexus and the Olive Tree',
      genre: 'non-fiction',
      type: 'Book',
      digital_link: 'https://test.com/Book1_Name.pdf',
      amount: 20348,
      status: 'pending',
      tags: ['nonfiction', 'Germany', 'Book'],
      date_added: '2022-11-14',
      date_published: '2023-07-12',
    },
    // ...
  ];